name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create environment file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Install Dependencies
        run: |
          npm install
          npm run build

      - name: Remove modules
        run: |
          rm -r node_modules

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./
          remote_path: ${{secrets.PROJECT_PATH}}
          remote_host: ${{ secrets.HOST }}
          remote_user: root
          remote_key: ${{ secrets.SERVER_SSH_KEY }}

      - name: SSH into Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{secrets.PROJECT_PATH}}
            export PATH=$PATH:${{ secrets.NODE_PATH }}
            npm i
            npx prisma db push
            pm2 restart all
